# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20180211_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='released_date',
            field=models.DateField(default=None),
        ),
    ]
